# Generated by Django 5.0.7 on 2024-09-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="추가된 일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정된 일시"),
                ),
                (
                    "product_name",
                    models.CharField(max_length=100, verbose_name="상품명"),
                ),
                ("purity", models.FloatField(verbose_name="순도")),
                ("price_per_gram", models.FloatField(verbose_name="그램 당 금액")),
                (
                    "crr_stock_per_gram",
                    models.IntegerField(verbose_name="그램 당 현재 보유량"),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "product",
            },
        ),
    ]
